export { default as Home } from "./Home/home";
export { default as Login } from "./Login/login";
export { default as Register } from "./Register/register";
export { default as Profile } from "./Profile/profile";
export { default as Catalog } from "./Catalog/catalog";
export { default as AddUser } from "./AddUser/addUser";
export { default as AddBook } from "./AddBook/addBook";
export { default as UserList } from "./UsersList/usersList";
export { default as Notifications } from "./Notifications/notications"
export { default as NotFound } from "./NotFound/notFound";
export { default as NotAuthenticated } from "./NotFound/notFound";
export { default as AcessDenied } from "./AcessDenied/acessDenied";
